- hosts: all

  tasks:

    - name: Get disk usage
      command: df -h
      register: disk_usage

    - name: Check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage

    # Send Discord message when disk space is over 80%
    - name: Send Discord message
      uri:
        url: "https://discord.com/api/webhooks/1216074834040066058/sjiI88ou38x5mRxkNOu_GLmITB6Rc8JgafVeYqXqTRafYtKG8x-AEixMTFtc2yzyMQ69"
        method: POST
        body_format: json
        body: '{"content": "Disk space on {{ inventory_hostname }} is above 40%!"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: disk_usage.stdout[:-1]|int > 40
